[project]
name = "mobility-function"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "azure-functions>=1.21.3",
    "azure-storage-blob>=12.24.0",
    "pandas>=2.2.3",
    "pytz>=2024.2",
    "requests>=2.32.3",
]
